# Script to create the recommendations table
from db import get_connection, DBError

conn = get_connection()
cursor = conn.cursor()

# Create recommendations table
cursor.execute('''
    CREATE TABLE IF NOT EXISTS recommendations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id BIGINT NOT NULL,
        disorder_type TEXT NOT NULL,
        recommendation_text TEXT NOT NULL,
        recommendation_details TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
    );
''')

conn.commit()
cursor.close()
conn.close()

print('Recommendations table created successfully!')
